version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    image: postgres_online_store
    container_name: online_store_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: online_store
    ports:
      - "5432:5432"  # Мапінг порту PostgreSQL
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
